### ISSUE TITLE
README is confusing for me

### ISSUE THREAD

**Issue by probil** [yantrashala/loopback-ssl#14]
`httpMode` is not correctly described in docs. I'm confused

### Setup Configuration (says for SSL it should be `false`)

> `"httpMode": false`

### Disable HTTPS (says for SSL it should be `true`)

> The configuration entry "httpMode": false will disable https.

### Enable SSL (says for SSL it should be `true`)

> `  "httpMode": true`

### Enable Mutual SSL (says for SSL it should be `true`)

> `  "httpMode": true,`

--- 
On app start with `"httpMode": false` (!):
```
Web server listening at: http://0.0.0.0:8080
Browse your REST API at http://0.0.0.0:8080/explorer
```

And with `"httpMode": true` (!):
```
Web server listening at: https://0.0.0.0:8080
Browse your REST API at https://0.0.0.0:8080/explorer
```

**Comment by slahiri** [comment]
This will be a breaking change for people already using the module. What do you suggest we can document further in README to make this more clear and easy?

**Comment by slahiri** [comment]
Updated the readme documentation to make it less complicated without making any breaking changes.
