### ISSUE TITLE
Question: http and https?

### ISSUE THREAD

**Issue by msimonc** [yantrashala/loopback-ssl#22]
Thanks for this, https works!

Question: Would it be possible to have both http and https working at the same time?

(typo in the Readme: "httpMode": flase)

**Comment by slahiri** [comment]
@msimonc, right now, this module enables https for the loopback app (extended from express). One service cannot run on two ports, if you want you can create two app instances referencing to same model. Load one as http and the other as https.

**Comment by slahiri** [comment]
Hope the reply works. Closing the issue.

**Comment by msimonc** [comment]
Thanks for this, 
from Sydney
