### ISSUE TITLE
Use this module to force already configured SSL server

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [yantrashala/loopback-ssl#25]
If a server is already configured for SSL ..

Can this module be used to force SSL not configuring it?

**Comment by slahiri** [comment]
Request if you can explain the question with some context.

**Comment by slahiri** [comment]
@ahmed-abdulmoniem - did not heard anything form you on the question. Request if you can provide more context so that I can reply.

**Comment by slahiri** [comment]
Closing issue. If we see similar questions, will re-open in future.

**Comment by ahmed-abdulmoniem** [comment]
@slahiri Sorry for the delay
I mean already my SSL is on .. but I need just to force the SSL redirect when someone tries to open the API for example.
