### ISSUE TITLE
How to avoid getting Red Warnings on browsers (because of self-signed certificate)

### ISSUE THREAD

**Issue by rogerlopz** [yantrashala/loopback-ssl#33]
Hi, i followed all the instructions here, wich btw, are pretty clear but i cant get my loopback API to work.

I have used the following script:

```
#!/bin/bash

# https://github.com/strongloop/loopback-gateway/blob/master/server/private/ssl-keygen.sh

KEY_LENGTH=2048

# Generate CA
# openssl genrsa -des3 -out ca.key $KEY_LENGTH
# openssl req -new -key ca.key -out ca.csr
# openssl x509 -req -in ca.csr -out ca.crt -signkey ca.key

# Generate server key
openssl genrsa -passout pass:1234 -des3 -out server.key $KEY_LENGTH
openssl req -passin pass:1234 -new -key server.key -out server.csr

# Remove the passphrase
cp server.key server.key.org
openssl rsa -passin pass:1234 -in server.key.org -out server.key

# Generate server certificate
openssl x509 -req -days 730 -in server.csr -signkey server.key -out server.pem
cp server.pem certificate.pem
cp server.key privatekey.pem
rm server.pem server.key server.key.org server.csr
```
Wich generates `privatekey.pem` and `certificate.pem` files.

And once added on my config.json we have this block:

```
"httpMode": false,
  "certConfig": {
    "path": "server/ssl/",
    "key": "privatekey.pem",
    "cert": "certificate.pem",
    "ca": [],
    "requestCert": false,
    "rejectUnauthorized": false
  }
```
But i keep getting these erros:
![api error](https://user-images.githubusercontent.com/4995589/31682688-19af9bc6-b338-11e7-9236-b7267da6c4a8.png)
![api error 2](https://user-images.githubusercontent.com/4995589/31682756-4cb9a962-b338-11e7-8f80-de6e91fbdde6.png)

Whay can i do to fix that?

My shared hosting provider auto-generates SSL certificates with letsencrypt and there is one generated for my subdomain (api.mywebsite.com) but those files are in a folder called SSL and inside are three folders certs, csrs(empty) and keys and inside those folders there are files that end with an extension of .crt and .key but i dont know how to use them nor the ones generated with openssl.

Any hints?

Any hints?

**Comment by slahiri** [comment]
Since you are using self signed certificates, Chrome will complain. Stackoverflow article (pretty detailed) -  [Getting Chrome to accept self-signed localhost certificate](https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate).

**Comment by rogerlopz** [comment]
Hi @slahiri 
Thanks for your response and sorry if i didnt update my issue but i have fixed it.
What i did was to copy the content of a working ssl certificate into my .pem files and it worked!
Thanks again for your work with this module, you can close this issue.
